### ISSUE TITLE
dashes are removed in strings

### ISSUE THREAD

**Issue by mlennie** [SeyZ/jsonapi-serializer#29]
Hello currently I have a deep array that is stored as Business.availability.hoursOfOperation.exception. exception is an array. In postgres it is stoerd as ["2015-09-21", "2015-09-23", "2015-09-25"] although passing Business into the serializer it comes out as ["20150914", "20150922", "20150924"]. It appears the dashes are gone. Is the attribute possibly too deeply nested? Thanks for your help!

**Comment by jamesdixon** [comment]
@SeyZ to give some additional background on this, as @mlennie said, we have a data structure containing an array that contains elements with dashes in them. It should also be noted that we're using a custom `keyForAttribute` function to camelCase our keys:

```javascript
// camelize attribute names
options.keyForAttribute = function(attribute) {
  return _.camelCase(attribute);
};
```
I tracked the issue down to the following [block of code](https://github.com/SeyZ/jsonapi-serializer/blob/master/lib/serializer-utils.js#L20). Essentially, when an array is detected, it maps the `keyForAttribute` function to each item in the array. The issue is that it's treating every item in the array as a complex object. However, if it's just a primitive, then that value is eventually passed back to the custom `keyForAttribute` function. In our case, this caused the dates containing the dashes to be camelCased, which using lodash, removes the dashes. Note that if you were using `inflection.camelize()` nothing happens as it ignores dashes.

This was certainly an edge case given our specific set of circumstances, but ultimately, the issue is that primitive values should not be passed to the `keyForAttribute` function.

**Comment by jamesdixon** [comment]
@SeyZ if you'd like to test what we described, I've included a new test in my PR called: **keyForAttribute - should ignore non-complex array items** Copy that into the current test suite and run it (make sure to include lodash in your test file).

Thanks!
